// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvevwuisnlyhnohonwzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2ZXZ3dWlzbmx5aG5vaG9ud3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzA2MDQsImV4cCI6MjA2ODUwNjYwNH0.2bm5C4icpFe099eduu6lc1u-mqWzSvFginU5T6NCbxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});